# Generated by Django 5.1 on 2024-09-17 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_compras_quantidadeprodutos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='produtosComprados',
        ),
        migrations.AddField(
            model_name='compras',
            name='produtoComprado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.produto'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente'),
        ),
    ]
