# Generated by Django 5.1 on 2024-09-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_compras_produtoscomprados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='pagamento',
            field=models.BooleanField(default=False),
        ),
    ]
